/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : LIBJPN
 #	author : miyako
 #	12/07/20
 #
 # --------------------------------------------------------------------------------*/



// --- ICU
//void ICU_GET_ENCODING_LIST(sLONG_PTR *pResult, PackagePtr pParams);
//void ICU_Get_good_encodings(sLONG_PTR *pResult, PackagePtr pParams);
//void ICU_Get_best_encoding(sLONG_PTR *pResult, PackagePtr pParams);
//void ICU_Normalize_text(sLONG_PTR *pResult, PackagePtr pParams);
//void ICU_Transform_text(sLONG_PTR *pResult, PackagePtr pParams);
//void ICU_Get_error_text(sLONG_PTR *pResult, PackagePtr pParams);
//void ICU_Convert_to_text(sLONG_PTR *pResult, PackagePtr pParams);
//void ICU_Convert_from_text(sLONG_PTR *pResult, PackagePtr pParams);

// --- mecab
//void mecab(sLONG_PTR *pResult, PackagePtr pParams);

// --- iconv
//void iconv(sLONG_PTR *pResult, PackagePtr pParams);

// --- JIS
//void JIS_Convert_to_text(sLONG_PTR *pResult, PackagePtr pParams);
//void JIS_Convert_from_text(sLONG_PTR *pResult, PackagePtr pParams);
